sudo: required
services:
    - docker
language: bash
env:
    global:
        - NAME=montreal
        - REPO_URL="https://github.com/r3r57/MonTreAL.git"
        - VERSION=latest
    matrix:
        - ARCH=-amd64 DOTARCH=.amd64
        - ARCH=-arm DOTARCH=.arm
before_script: make fetch
script: make build
after_success: make push
after_failure: make clean
