sudo: required
services:
    - docker
language: bash
env:
    global:
        - NAME=montreal
        - REPO_URL="https://github.com/r3r57/MonTreAL.git"
        - VERSION=latest
    matrix:
        - ARCH=-amd64 DOTARCH=.amd64
        - ARCH=-arm DOTARCH=.arm
script: 
    - make fetch
    - make build
    - make push
