sudo: required
services:
    - docker
language: bash
branches:
  only:
    - master
env:
    global:
        - NAME=montreal
        - REPO_URL="https://github.com/r3r57/MonTreAL.git"
        - VERSION=latest
    matrix:
        - ARCH=-amd64 DOTARCH=.amd64
        - ARCH=-arm DOTARCH=.arm
before_install:
  - docker pull "${DOCKER_USER}/${NAME}:${VERSION}${ARCH}"
script: make

jobs:
  include:
    - stages Make Manifest
      script: make manifest
